dags:
  - dag_id: api_call_1
    schedule_interval: "0 6 * * *"  # Example: Run daily at 6 AM
    api_endpoint: "https://api.example.com/endpoint1"
    target_dataset: "bigquery_landing_dataset_1"
    destination_table: "landing_table_1"
  - dag_id: api_call_2
    schedule_interval: "0 12 * * *"  # Example: Run daily at 12 PM
    api_endpoint: "https://api.example.com/endpoint2"
    target_dataset: "bigquery_landing_dataset_2"
    destination_table: "landing_table_2"
